#Define all services in the project
services:
    adoy_oauth_client:
        class: OAuth2\Client
        arguments: ['%oauth_fitbit_client_id%','%oauth_fitbit_client_secret%',1]
    fitbit_oauth_client:
        class: FitbitOAuth\ClientBundle\Service\FitbitOAuth2Client
        arguments:  ['@adoy_oauth_client','%fitbit_api_urls%','authorization_code','activity heartrate location nutrition profile sleep']
    fitbit_jwt_token_service:
        class: FitbitOAuth\ClientBundle\Service\TokenService
        arguments:  ['%jwt_client_id%','%jwt_client_secret%']
    fitbit_user_provider:
        class: FitbitOAuth\ClientBundle\Security\UserProvider
    fitbit_jwt_authenticator:
        class:  FitbitOAuth\ClientBundle\Security\JWTAuthenticator
        arguments: ['@fitbit_jwt_token_service']
        public: false
    email_handler:
        class: FitbitOAuth\ClientBundle\Service\EmailService
        arguments: ['@service_container','%mailer_from_address%']
