parameters:
    oauth_fitbit_client_id: 227HZF
    oauth_fitbit_client_secret: 0a856487889789c6f6ca1c691fdd9cc3
    fitbit_api_urls:
       oauth_token_endpoint: https://api.fitbit.com/oauth2/token
       oauth_authorize_endpoint: https://www.fitbit.com/oauth2/authorize
       oauth_redirect_uri: https://www.pavans-world.com/fitbit/api/subscribe
       user_api: 
         profile: "https://api.fitbit.com/1/user/[user-id]/profile.json"
         sleep: "https://api.fitbit.com/1/user/[user-id]/sleep/date/[date].json"
         activites_subscribe: "https://api.fitbit.com/1/user/-/activities/apiSubscriptions/[subscription-id].json"
         sleep_subscribe: "https://api.fitbit.com/1/user/-/sleep/apiSubscriptions/[subscription-id].json"

    #my custom JWT Settings
    jwt_client_id: "mycustomclient"
    jwt_client_secret: "mycustomsecret"


services:
    adoy_oauth_client:
        class: OAuth2\Client
        arguments: ['%oauth_fitbit_client_id%','%oauth_fitbit_client_secret%',1]
    fitbit_oauth_client:
        class: FitbitOAuth\ClientBundle\Service\FitbitOAuth2Client
        arguments:  ['@adoy_oauth_client','%fitbit_api_urls%','authorization_code','activity heartrate location nutrition profile sleep']
    fitbit_jwt_token_service:
        class: FitbitOAuth\ClientBundle\Service\TokenService
        arguments:  ['%jwt_client_id%','%jwt_client_secret%']
    fitbit_user_provider:
        class: FitbitOAuth\ClientBundle\Security\UserProvider
    fitbit_jwt_authenticator:
        class:  FitbitOAuth\ClientBundle\Security\JWTAuthenticator
        arguments: ['@fitbit_jwt_token_service']
        public: false