imports:
    - { resource: parameters.yml }
  # - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@FitbitOAuthClientBundle/Resources/config/services.yml" }
    - { resource: "@FitbitOAuthClientBundle/Resources/config/security.yml" }
    - { resource: "@FitbitOAuthClientBundle/Resources/config/parameters.yml" }
    - { resource: "@FitbitOAuthClientBundle/Resources/config/config.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    secret: "myapp"

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    #paths:  
     #   '%kernel.root_dir%/../src/FitbitOAuth/ClientBundle/Resources/views/': ~

monolog:
    handlers:
        applog:
            type: stream
            path: /var/log/symfony.log
            level: error
        main:
            type: fingers_crossed
            action_level: warning
            handler: file
        file:
            type: stream
            level: debug
        syslog:
            type: syslog
            level: error
        console:
            type:   console
            verbosity_levels:
                VERBOSITY_NORMAL: INFO
            formatter: my_formatter

jwt_auth:
    client_id:     KNuydwEqwGsPNpxdAhACmOWDUmBEZsLn
    client_secret: cQT57M1wIYvcW1Rr6lTGWitqlkBtYwsyYkHG-mhVKdxhXBATWDwM6tB0mJFJVWFv
    domain: wptest.auth0.com
